- 2026-03-20 수업 중 실습
- `iris` 학습 데이터를 라이브러리로 불러오기

In [21]:
# 여기서 다루는 데이터는 로컬 데이터가 아니라
# 라이브러리 통해 load_iris()로 가져옴에 유의

from sklearn import datasets
data = datasets.load_iris()
X = data.data
y = data.target

In [22]:
# 공통 라이브러리 선언

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import pandas as pd
import numpy as np

# **logistic-regression**

In [23]:

from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

clf_lr = LogisticRegression(random_state=0, max_iter=200)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


# **decision-tree**

In [24]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


# **random-forest**

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

from sklearn.ensemble import RandomForestClassifier

clf_rf = RandomForestClassifier(random_state=0)
clf_rf.fit(X_train, y_train)

pred_rf = clf_rf.predict(X_test)

print ("\n--- Random Forest Classifier ---")
print (accuracy_score(y_test, pred_rf))
print (confusion_matrix(y_test, pred_rf))


--- Random Forest Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


# **KNN**

In [26]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

pred = knn.predict(X_test)
print("KNN Accuracy:", accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))

KNN Accuracy: 0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
